---
substitutions:
  # Device information
  # Requirements for the device name: https://esphome.io/components/esphome.html
  deviceid: shelly-plug-office-desk-daniel # marked as: SP2
  devicename: "Office: Plug Desk Daniel"
  channel_1: Relay

  # Password and Encryption Key for Home Assistant API, OTA Updates, and Web UI
  password: !secret password
  api_encryption_key: !secret api_encryption_key

  # Wifi connection data
  ssid: !secret wifi_ssid
  wifi_password: !secret wifi_password

  # Higher value gives lower watt readout
  current_res: "0.000943"
  # Lower value gives lower voltage readout
  voltage_div: "1820"
  # measure a relatively strong load and enter values measured by the device vs the values your reference measurement provided here
  power_cal_meas: "1420.0"
  power_cal_real: "1350.0"

  # Used for automated shutdown/protection
  max_power: "2400"
  max_temp: "70.0"

esphome:
  name: ${deviceid}

esp8266:
  board: esp8285

wifi:
  ssid: ${ssid}
  password: ${wifi_password}

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${deviceid}
    password: ${wifi_password}
    manual_ip:
      static_ip: 192.168.100.2
      gateway: 192.168.100.1
      subnet: 255.255.255.0
      dns1: 1.1.1.1
      dns2: 1.0.0.1

captive_portal:

logger:
  level: WARN

# Expose Home Assistant API
api:
  encryption:
    key: ${api_encryption_key}

ota:
  safe_mode: true
  num_attempts: 10
  password: ${password}

web_server:
  port: 80
  auth:
    username: admin
    password: ${password}

time:
  - platform: sntp
    id: sntp_time

binary_sensor:
  # Button
  - platform: gpio
    pin:
      number: GPIO13
      inverted: true
    name: "${devicename}: Button"
    on_press:
      - switch.toggle: relay

status_led:
  pin:
    number: GPIO02
    inverted: true

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  # Relay
  - platform: gpio
    pin: GPIO15
    id: relay
    name: "${devicename}: ${channel_1}"
    restore_mode: RESTORE_DEFAULT_ON

sensor:
  # Wifi
  - platform: wifi_signal
    name: "${devicename}: WiFi Signal"
    icon: "mdi:wifi"
    update_interval: 300s

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: "${devicename}: Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: ${max_temp}
        then:
          - switch.turn_off: relay
          - homeassistant.service:
              service: persistent_notification.create
              data:
                title: "Message from ${devicename}"
              data_template:
                message: "Switch turned off because temperature exceeded ${max_temp}°C"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

  # Voltage, Current, Power
  - platform: hlw8012
    model: BL0937
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${devicename}: Current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      icon: "mdi:flash-outline"
    voltage:
      name: "${devicename}: Voltage"
      unit_of_measurement: "V"
      icon: "mdi:flash-outline"
    power:
      name: "${devicename}: Power"
      id: power
      unit_of_measurement: "W"
      filters:
        - calibrate_linear:
            - 0.0 -> 0.0
            - ${power_cal_meas} -> ${power_cal_real}
      icon: "mdi:flash-outline"
      on_value_range:
        - above: ${max_power}
          then:
            - switch.turn_off: relay
            - homeassistant.service:
                service: persistent_notification.create
                data:
                  title: "Message from ${devicename}"
                data_template:
                  message: "Switch turned off because power exceeded ${max_power}W"
    update_interval: 10s

  # Aggregates
  - platform: total_daily_energy
    name: "${devicename}: Daily Energy"
    power_id: power
    filters:
      # Multiplication factor from W to kW is 0.001
      - multiply: 0.001
    unit_of_measurement: kWh
    icon: "mdi:flash-outline"

text_sensor:
  - platform: version
    name: "${devicename}: Version"
    hide_timestamp: true
    icon: "mdi:car-esp"
